/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.handong.csee.java.javaFinalProject;

import java.io.File;
import java.util.ArrayList;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;

import edu.handong.csee.java.javaFinalProject.datamodel.graphT;
import edu.handong.csee.java.javaFinalProject.datamodel.summaryT;
import edu.handong.csee.java.javaFinalProject.utils.Utils;;

public class Library {

	String input;
	String output;
	boolean help;

	public boolean someLibraryMethod() {
		return true;
	}

	public void run(String[] args) {

		Options option = createOptions();
		if (parseOptions(option, args)) {
			if (help) {
				printHelp(option);
				return;
			}

		} else {
			System.exit(0);
		}
		try {

			// when there are not enough arguments from CLI, it throws the
			// NotEnoughArgmentException which must be defined by you.
			if (args.length < 2)
				throw new Exception();
		} catch (Exception e) {
			System.out.println(e.getMessage());
			System.exit(0);
		}

		String dataPath = input; // csv file to be analyzed
		String resultPath = output; // the file path where the results are saved.

		ArrayList<String> fileNames = new ArrayList<String>();
		ArrayList<String> dataPaths = new ArrayList<String>();

		File file = new File(dataPath);

		// 1. check if the file exists or not
		boolean isExists = file.exists();

		if (!isExists) {
			System.out.println("There is nothing.");
		}

		// 2. check if the object is directory or not.
		if (file.isDirectory()) {
			File[] fileList = file.listFiles();
			for (File tFile : fileList) {
				// System.out.print(tFile.getName());
				fileNames.add(tFile.getName());
				dataPaths.add(dataPath + "/" + tFile.getName());

			}
		} else {
			System.out.println("It is not a directory.");
		}
		System.out.println("dataPaths : " + dataPaths);

		System.out.println("summarys ------------------------------------- S");
		ArrayList<summaryT<String>> totalSummarys = new ArrayList<summaryT<String>>();
		ArrayList<graphT<String>> totalGraphs = new ArrayList<graphT<String>>();
		int i = 0;
		for (String name : fileNames) {
			String path = dataPath + "/" + name;
			if (path.contains("DS_Store"))
				continue;
			ArrayList<summaryT<String>> summarys = Utils.ZipReaderSummary(path, name);
			ArrayList<graphT<String>> graphs = Utils.ZipReaderGraph(path, name);
			i=0;
			for (summaryT<String> num : summarys) {
				totalSummarys.add(summarys.get(i));
				i++;
			}
			i=0;
			for (graphT<String> num : graphs) {
				totalGraphs.add(graphs.get(i));
				i++;
			}
		}

		// ArrayList<summaryT<String>> summarys = Utils.ZipReaderSummary(dataPath);
		// ArrayList<graphT<String>> graphs = Utils.ZipReaderGraph(dataPath);
//		System.out.println("summarys ------------------------------------- E");
//		if (summarys == null) {
//			System.out.println("summarys is null");
//		} else {
//			for (int i = 0; i < summarys.size(); i++) {
//				System.out.println("====>>>> [" + i + "]" + summarys.get(i).toString());
//
//			}
//		}
//
//		if (graphs == null) {
//			System.out.println("graphs is null");
//		} else {
//			for (int i = 0; i < graphs.size(); i++) {
//				System.out.println("====>>>> [" + i + "]" + graphs.get(i).toString());
//
//			}
//		}
		Utils.writeexcelSummary(totalSummarys);
		Utils.writeexcelGraph(totalGraphs);

	}

	private boolean parseOptions(Options options, String[] args) {
		CommandLineParser parser = new DefaultParser();

		try {

			CommandLine cmd = parser.parse(options, args);

			input = cmd.getOptionValue("i");
			output = cmd.getOptionValue("o");
			help = cmd.hasOption("h");

		} catch (Exception e) {
			printHelp(options);
			return false;
		}

		return true;
	}

	private Options createOptions() {
		Options options = new Options();

		// add options by using OptionBuilder
		options.addOption(Option.builder("i").longOpt("input").desc("Set an input file path").hasArg()
				.argName("Input path").required().build());

		options.addOption(Option.builder("o").longOpt("output").desc("Set an input file path").hasArg()
				.argName("Output path").required().build());

		// add options by using OptionBuilder
		options.addOption(Option.builder("h").longOpt("help").desc("Help").build());

		return options;
	}

	private void printHelp(Options options) {
		// automatically generate the help statement
		HelpFormatter formatter = new HelpFormatter();
		String header = "HGU Course Analyzer";
		String footer = "";
		formatter.printHelp("HGUCourseCounter", header, options, footer, true);
	}

}
